# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'XXBRefreshDemo' do
pod 'XXBRefresh', :path => '../'
pod 'XXBLibs', :git => "https://github.com/sixTiger/XXBLibs"
end

